// Shared, fully-typed fixtures for the backend test suite.
//
// Every builder returns a complete object of the production type so a mock
// such as `vi.mocked(getWorkspace).mockReturnValue(makeWorkspace())` type-checks
// against the real service signature. Defaults are deliberately neutral
// (null / '' / false / [] / 0) so a test only spells out what it cares about.
//
// Only `import type` here: this module must never load production code, since
// test files `vi.mock()` these services before importing anything else.
import type { EffectiveSettings, GlobalSettings, ProjectSettings } from '../../server/services/settings-service.js'
import type { Task, Workspace, WorkspaceWithTasks } from '../../server/services/workspace-service.js'

export function makeWorkspace(overrides: Partial<Workspace> = {}): Workspace {
  return {
    id: 'ws-1',
    name: 'Test Workspace',
    projectPath: '/tmp/project',
    sourceBranch: 'main',
    workingBranch: 'feature/test',
    worktreePath: '/tmp/project/.worktrees/feature/test',
    worktreeOwned: true,
    status: 'idle',
    notionUrl: null,
    notionPageId: null,
    sentryUrl: null,
    prUrl: null,
    model: 'claude-opus-4-6',
    brainstormModel: null,
    reasoningEffort: 'auto',
    agentPermissionMode: 'bypass',
    devServerStatus: 'stopped',
    hasUnread: false,
    archivedAt: null,
    favoritedAt: null,
    prWatchDisabledAt: null,
    tags: [],
    description: null,
    agentDescription: null,
    initialPrompt: null,
    prChangesDismissedAt: null,
    prCiFailureDismissedAt: null,
    worktreePurgedAt: null,
    worktreePurgeRestoreData: null,
    comparisonId: null,
    engine: 'claude-code',
    autoLoop: false,
    autoLoopReady: false,
    noProgressStreak: 0,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    ...overrides,
  }
}

export function makeTask(overrides: Partial<Task> = {}): Task {
  return {
    id: 'task-1',
    workspaceId: 'ws-1',
    title: 'Task 1',
    status: 'pending',
    isAcceptanceCriterion: false,
    sortOrder: 0,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    ...overrides,
  }
}

export function makeWorkspaceWithTasks(overrides: Partial<WorkspaceWithTasks> = {}): WorkspaceWithTasks {
  return { ...makeWorkspace(), tasks: [makeTask()], ...overrides }
}

export function makeEffectiveSettings(overrides: Partial<EffectiveSettings> = {}): EffectiveSettings {
  return {
    model: 'auto',
    dangerouslySkipPermissions: true,
    prPromptTemplate: '',
    reviewPromptTemplate: '',
    ciFixPromptTemplate: '',
    notionInitialPromptTemplate: '',
    sentryInitialPromptTemplate: '',
    gitConventions: '',
    sourceBranch: 'main',
    devServer: null,
    setupScript: '',
    cleanupScript: '',
    cleanupScriptMode: 'no-tasks',
    cleanupScriptOnlyOnChanges: false,
    archiveScript: '',
    changeSourceBranchScript: '',
    sessionEndedScript: '',
    prMergedScript: '',
    autoLoopDisabledScript: '',
    notionStatusProperty: '',
    notionInProgressStatus: '',
    ...overrides,
  }
}

export function makeProjectSettings(overrides: Partial<ProjectSettings> = {}): ProjectSettings {
  return {
    path: '/tmp/project',
    displayName: '',
    defaultSourceBranch: '',
    defaultModel: '',
    dangerouslySkipPermissions: true,
    prPromptTemplate: '',
    reviewPromptTemplate: '',
    ciFixPromptTemplate: '',
    notionInitialPromptTemplate: '',
    sentryInitialPromptTemplate: '',
    gitConventions: '',
    setupScript: '',
    taskPromptTemplate: '',
    cleanupScript: '',
    cleanupScriptMode: '',
    archiveScript: '',
    changeSourceBranchScript: '',
    sessionEndedScript: '',
    prMergedScript: '',
    autoLoopDisabledScript: '',
    devServer: { startCommand: '', stopCommand: '' },
    e2e: { framework: '', skill: '', prompt: '' },
    finalization: { prompt: '' },
    color: null,
    forge: 'auto',
    ...overrides,
  }
}

/**
 * Neutral global settings: every prompt template empty, every per-engine map
 * empty and `skillSuite: 'custom'` with blank overrides, so prompt builders
 * fall back to their agnostic defaults exactly as they did when the mocks
 * returned partial objects.
 */
export function makeGlobalSettings(overrides: Partial<GlobalSettings> = {}): GlobalSettings {
  return {
    defaultModelByEngine: {},
    dangerouslySkipPermissions: true,
    prPromptTemplate: '',
    reviewPromptTemplate: '',
    ciFixPromptTemplate: '',
    finalizationPrompt: '',
    notionInitialPromptTemplate: '',
    sentryInitialPromptTemplate: '',
    gitConventions: '',
    setupScript: '',
    cleanupScript: '',
    cleanupScriptMode: 'no-tasks',
    cleanupScriptOnlyOnChanges: false,
    archiveScript: '',
    changeSourceBranchScript: '',
    sessionEndedScript: '',
    prMergedScript: '',
    autoLoopDisabledScript: '',
    editorCommand: '',
    fileManagerCommand: '',
    terminalCommand: '',
    autoPurgeOnPrMerged: false,
    autoLoopMaxRetries: 5,
    awaitingUserReminderMinutes: 0,
    maxConcurrentAgents: 0,
    wsEventsRetentionDays: 0,
    wsEventsKeepPerWorkspace: 0,
    networkAccessEnabled: false,
    networkAccessToken: '',
    networkAccessBehindProxy: false,
    browserNotifications: true,
    audioNotifications: true,
    audioQuestionNotifications: false,
    audioWorkspaceCreatedNotifications: false,
    audioAgentErrorNotifications: false,
    audioNotificationSound: '',
    audioQuestionSound: '',
    audioWorkspaceCreatedSound: '',
    audioAgentErrorSound: '',
    audioPrCiFailedSound: '',
    audioPrCiFailedEnabled: false,
    audioPrCiFailedVolume: 1,
    audioPrCiRecoveredSound: '',
    audioPrCiRecoveredEnabled: false,
    audioPrCiRecoveredVolume: 1,
    audioPrChangesRequestedSound: '',
    audioPrChangesRequestedEnabled: false,
    audioPrChangesRequestedVolume: 1,
    audioPrApprovedSound: '',
    audioPrApprovedEnabled: false,
    audioPrApprovedVolume: 1,
    audioPrMergeConflictSound: '',
    audioPrMergeConflictEnabled: false,
    audioPrMergeConflictVolume: 1,
    audioPrReadyToMergeSound: '',
    audioPrReadyToMergeEnabled: false,
    audioPrReadyToMergeVolume: 1,
    audioPrMergedSound: '',
    audioPrMergedEnabled: false,
    audioPrMergedVolume: 1,
    audioNotificationVolume: 1,
    audioQuestionVolume: 1,
    audioWorkspaceCreatedVolume: 1,
    audioAgentErrorVolume: 1,
    notionStatusProperty: '',
    notionInProgressStatus: '',
    notionAssigneeProperty: '',
    notionUserId: '',
    defaultPermissionModeByEngine: {},
    notionMcpKey: '',
    sentryMcpKey: '',
    bitbucketToken: '',
    bitbucketUsername: '',
    notionEnabled: true,
    sentryEnabled: true,
    showThinkingBlocks: true,
    whipEnabled: false,
    whipShortcut: '',
    whipVolume: 1,
    tags: [],
    branchPrefixes: [],
    worktreesPath: '.worktrees',
    worktreesPrefixByProject: false,
    voiceEnabled: false,
    voicePttKey: 'alt',
    voiceLanguage: 'auto',
    voiceModel: null,
    voiceCommandPath: '',
    voiceFfmpegPath: '',
    voiceTemperature: 0,
    voicePrompt: '',
    voiceTranslateToEnglish: false,
    voiceSuppressNonSpeechTokens: true,
    flattenWorkspaceList: false,
    skillSuite: 'custom',
    customReviewTemplate: '',
    customAutoLoopReviewGate: '',
    customAutoLoopGroomingIntro: '',
    customQaPromptTemplate: '',
    customBrainstormingInstruction: '',
    ...overrides,
  }
}
